### ISSUE TITLE
云服务器docker搭建自动领京豆bot互动指令 | YongsBlog

### ISSUE THREAD

**Issue by yong-s** [yong-s/yong-s.github.io#1]
https://yong-s.github.io/post/yun-fu-wu-qi-docker-da-jian-zi-dong-ling-jing-dou-bot-hu-dong-zhi-ling/ 

 使用docker部署自动领金豆bot脚本

使用的版本：
服务器：centos 8
docker： 20.10.6
docker-compose： 1.27.4
1、服务器安装docker，docker-compose
推荐使用centos...

**Comment by CoderAWei** [comment]
你好，按照你的教程配置是ok的。但我想请问两个问题。
1. 开启tg推送之后docker里的定时任务全都没了。请问知道是什么原因吗？
2. tg推送能收到，但如何能做成交互式的那种呢？机器人里输入/spnode等命令，我在YouTube看到说国内服务器不支持bot功能

**Comment by yong-s** [comment]
> @CoderAWei
> 你好，按照你的教程配置是ok的。但我想请问两个问题。
> 1. 开启tg推送之后docker里的定时任务全都没了。请问知道是什么原因吗？
> 2. tg推送能收到，但如何能做成交互式的那种呢？机器人里输入/spnode等命令，我在YouTube看到说国内服务器不支持bot功能

作者的文档里写的很详细，建议仔细阅读；国内服务器是不支持，既然你的tg推送都能收，就表示已经在墙外了的
